### ISSUE TITLE
quadprog high level interface function

### ISSUE THREAD

**Issue by edljk** [JuliaOpt/MathProgBase.jl#112]
Is there a specific reason for the following definition in
MathProgBase/src/HighLevelinterface/quadrpog.jl

quadprog(c,Q,A,rowlb,rowub,solver::AbstractMathProgSolver=defaultQPsolver) = quadprog(c,Q,A,rowlb,rowub,0,Inf,solver)

I would expect instead something like:

quadprog(c,Q,A,rowlb,rowub,solver::AbstractMathProgSolver=defaultQPsolver) = quadprog(c,Q,A,rowlb,rowub,-Inf,Inf,solver)

**Comment by mlubin** [comment]
Not particularly, but it's consistent with ``linprog`` whose shortened version is documented [here](http://mathprogbasejl.readthedocs.io/en/latest/linprog.html). I'm not sure how we could change this behavior at this point since it's silently breaking, unless we deprecate the shortened version and then a year later replace it with the new definition.

**Comment by edljk** [comment]
The -Inf,Inf formulation is the one I would expect but the modification is perhaps complicated for such a detail. I just wanted to be sure that this is not a mistake.

**Comment by mlubin** [comment]
Closing this then. If someone would like to revamp the high-level interfaces, PRs are accepted.
