### ISSUE TITLE
Add setrhs! method

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathProgBase.jl#142]
We currently have `setconstrUB!` and `setconstrLB!`, which would be complete for models without explicit equalities. But most solvers allow equalities and MathProgBase actually deals with both: senses `linprog(c, A, sense, b, l, u, solver)` and ranges `linprog(c, A, lb, ub, l, u, solver)`. Thus modifying models with equalities is weird by only setting ranges: suppose you want to modify an equality rhs, you would have to change LBs first (possibly to a higher value) and then you are temporarily inconsistent, so we would have to manage that in julia instead of keeping thin wrapper to solver...

Is a PR welcome? or this was already discussed?

**Comment by mlubin** [comment]
The LPQP solver interface has no concept of senses, ``linprog`` doesn't count.

What happens if a solver supports only ``setrhs!`` but not ``setconstrUB!`` and ``setconstrLB!``? What is JuMP supposed to do? What are users of MPB supposed to do? The philosophy so far has been that if the wrappers need to do a little bit of work (like maintaining consistency of bounds) to support a common interface, then better put that complexity in the solver wrapper than force it onto the users. There's no free lunch.

What MPB is missing now is a proper definition of which methods *must* be implemented and which methods are *optional*, and what it means to only implement a subset of the interface. I'm very hesitant to add new methods which introduce a new way to accomplish something that can already be done until we have a good solution to this issue.

The last two paragraphs apply directly to https://github.com/JuliaOpt/MathProgBase.jl/issues/40 as well.

**Comment by joaquimg** [comment]
Ok, that reasonable. Defining the _must_ methods is a good start.

And I think that a set of _optional_ methods would be awesome. 

Maybe we start by not exporting optional methods? (that would make it slightly clear that its not the default use)

**Comment by mlubin** [comment]
Not exported from where? The methods in ``SolverInterface`` aren't currently exported from ``MathProgBase``.

**Comment by joaquimg** [comment]
Good, my bad, I forgot.

Do currently have any thoughts about what to do with the optional methods?

Maybe a extension module: `MathProgExtras.jl`?

So the _must_ methods (with minimal redundancy) are in `MathProgBase.jl`, but the user can have access to some extras with the new module. I do understand it must be done carefully, otherwise we might end up with multiple sets of methods for multiple solvers.

**Comment by blegat** [comment]
Isn't it the purpose of `linprogsolvertest` and `linprogsolvertestextra` functions in `test/linproginterface.jl` ?
If a solver passes `linprogsolvertest` then it has implemented the mandatory interface and if it passes `linprogsolvertestextra` then it has implemented the optional interface.

**Comment by mlubin** [comment]
I don't see any need to put optional methods in a separate module. This is more of a documentation and testing issue.

**Comment by mlubin** [comment]
We might want to introduce a concept of one-sided linear constraints to MPB, but it's hard to see how ``setrhs!`` can be added as is.
